language: php
php:
  - 5.6
  - 7
  - hhvm
install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer require bower-asset/jquery.inputmask
  - composer update
  - composer info --installed
before_script:
  - mysql -e 'create database yii2_restx_test;'
  - cd tests  
  - php ./codeception/bin/yii  migrate/up --interactive=0
  - ../vendor/bin/codecept build
script: ../vendor/bin/codecept run unit --debug